# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 210f1e463e58519be11acfe5d89a55c6d79599653d7a8bf49952a7fe89cd8ccc9131ba9c03178169b602327a5318a3b6b722380687ce9fca853b5ee4f46306f0

test:
  secret_key_base: 4f760b3472be03a232f1c69742763e0a865dd00ed17d0a94813c0c23b38636262bddffb26f81395194103b4b60016bc2044f8e48c2659d2e400e259468117137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
